Feat/20 autoroles
Melvynx/codelynx-bot pull request #28
Opened 2024-10-14 22:01 UTC by Dercraker

- Ajout d'un serveur de webhook
- Nouvelle migration de la db du bot, pour ajout de table membre, product et bundle
- Ajout d'endpoint de webhook `/api/webhooks/codeline`
- deux type de webhook sont attendu, [Purshase](https://docs.codeline.app/docs/schools/webhooks/purshase) et [Refund](https://docs.codeline.app/docs/schools/webhooks/refund)

- close #20

NE PAS MERGE, ME LAISSER FAIRE @Dercraker MODIFICATION DE VAR D'ENV et AJOUT DES DATA EN DB A FAIRE LORS DU MERGE

2024-10-15 03:17 UTC, Melvynx requested changes

2024-10-15 03:17 UTC, Melvynx commented on src/utils/webhook/codeline-webhook.utils.ts
> +          },
```suggestion
          bundleId: bundle.id
```

2024-10-15 03:17 UTC, Melvynx commented on src/utils/webhook/codeline-webhook.utils.ts
> +    }));
ça me semble très étrange ça.

2024-10-15 03:17 UTC, Melvynx commented on prisma/schema.prisma
> +  bundle        Bundle[]
```suggestion
  bundles       Bundle[]
```

on comprends pas sinon

2024-10-15 11:14 UTC, Arcoz0308 requested changes

2024-10-15 11:14 UTC, Arcoz0308 commented on src/utils/prisma/queries/getBundle.query.ts
Pourquoi tu commences parfois les variables par une maj et parfois pas ? 🤔

2024-10-15 11:14 UTC, Arcoz0308 commented on src/utils/webhook/codeline-webhook.utils.ts
Utilise itemType plutot https://docs.codeline.app/docs/schools/webhooks/purshase

Ça fait moins bordelique

2024-10-15 11:14 UTC, Arcoz0308 commented on src/utils/webhook/codeline-webhook.utils.ts
> +  }
Utilise upsert plutot https://www.prisma.io/docs/orm/reference/prisma-client-reference#upsert

2024-10-15 11:14 UTC, Arcoz0308 commented on src/utils/webhook/codeline-webhook.utils.ts
> +
Upsert ici aussi

2024-10-15 19:36 UTC, Dercraker commented on prisma/schema.prisma
> +  bundle        Bundle[]
fix

2024-10-15 19:36 UTC, Dercraker commented on src/utils/prisma/queries/getBundle.query.ts
Comment ça ? Mes variables sont en minuscules

2024-10-15 19:36 UTC, Dercraker commented on src/utils/webhook/codeline-webhook.utils.ts
mb je l'avais surtout pas vu je fix sa

2024-10-15 19:36 UTC, Dercraker commented on src/utils/webhook/codeline-webhook.utils.ts
> +
fix

2024-10-15 19:36 UTC, Dercraker commented on src/utils/webhook/codeline-webhook.utils.ts
> +  }
fix

2024-10-15 19:43 UTC, Arcoz0308 commented on src/utils/prisma/queries/getBundle.query.ts
ici camelCase : https://github.com/Melvynx/codelynx-formation-discord-bot/blob/f8e4ecb512dd6b86fc83f082ee4d7f2a2fed6cf9/src/utils/webhook/codeline-webhook.utils.ts#L12
et la PascalCase https://github.com/Melvynx/codelynx-formation-discord-bot/blob/f8e4ecb512dd6b86fc83f082ee4d7f2a2fed6cf9/src/utils/prisma/queries/createNewMember.query.ts#L8

2024-10-16 04:00 UTC, Melvynx approved these changes

2024-10-16 18:40 UTC, merged