feat(ClosedTicketLimit): Add auto delete at the limit
Melvynx/codelynx-bot pull request #30
Opened 2024-10-22 19:02 UTC by Dercraker

Closes #29 
- [ ] Ajout de la var d'env `CLOSED_TICKET_LIMIT` avant de merge

2024-10-22 19:45 UTC, Arcoz0308 requested changes

2024-10-22 19:45 UTC, Arcoz0308 commented on src/events/closedTicketLimit/closedTicketLimit.class.ts
> +import type { ButtonBuilder, ClientEvents, Message, NonThreadGuildBasedChannel } from "discord.js";
fix enlint

2024-10-23 14:59 UTC, Dercraker commented on src/events/closedTicketLimit/closedTicketLimit.class.ts
> +import type { ButtonBuilder, ClientEvents, Message, NonThreadGuildBasedChannel } from "discord.js";
a ouais sa désactive mes actions on save ^^

C'est des trucs qui sont fait auto pour ma part sa x)

2024-10-23 15:30 UTC, Arcoz0308 approved these changes

2024-10-23 18:28 UTC, merged